version: '3.1'
services:
  database:
    image: postgres:9-alpine
    container_name: dbserver
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tododb
    ports:
     - "5432:5432"
    volumes:
     - tododb_data:/var/lib/postgresql/data
volumes:
  tododb_data: