server:
  port: 8080
  error:
    include-stacktrace: on_param
spring:
  application:
    name: todolist
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update